spring:
  application:
    name: employee-management
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/employee_management_db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

integration:
  cloudinary:
    url: ${CLOUDINARY_URL}

server:
  port: 8080